# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development do
  gem "rake", "~> 13.1"
  gem "rubocop", "~> 1.60"
  gem "rubocop-minitest", "~> 0.34.5"
  gem "rubocop-rake", "~> 0.6.0"
end

group :test do
  gem "minitest", "~> 5.21"
  gem "minitest-reporters", "~> 1.6"
end


