# frozen_string_literal: true

source "https://gem.coop"

gemspec

group :development do
  gem "guard"
  gem "guard-minitest"
  gem "rake", "~> 13.1"
  gem "rubocop", "~> 1.60"
  gem "rubocop-minitest", "~> 0.34.5"
  gem "rubocop-rake", "~> 0.6.0"
end

group :test do
  gem "minitest", "~> 5.21"
  gem "minitest-reporters", "~> 1.6"
  gem "timecop", "~> 0.9.8"
end
