#!/usr/bin/env ruby
# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title subsminder
# @raycast.mode fullOutput

# Optional parameters:
# @raycast.icon 💲

# Documentation:
# @raycast.author Eugene Chulkov
# @raycast.authorURL https://github.com/dev99problems

require_relative 'lib/utils/fetch'
require_relative 'lib/utils/print_buddy'

local = false
@active_subs = DataFetcher.new(local).active_subs

p = PrintBuddy.new
p.print_month_payout(@active_subs)
