#!/usr/bin/env ruby
# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title subsminder:y
# @raycast.packageName Yearly subscriptions
# @raycast.mode fullOutput

# Optional parameters:
# @raycast.icon 💰

# Documentation:
# @raycast.author Eugene Chulkov
# @raycast.authorURL https://github.com/dev99problems

require_relative 'lib/subs_minder/fetch'
require_relative 'lib/subs_minder/print_buddy'

duration = 'yearly'
active_subs = DataFetcher.new().active_subs(duration)

p = PrintBuddy.new(duration: duration)
p.print_active_payouts(active_subs)
